# Generated by Django 2.0.10 on 2019-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectiveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='effective_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='effective_date',
            field=models.ManyToManyField(to='employees.EffectiveDate'),
        ),
    ]
