# Generated by Django 2.0.10 on 2019-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190118_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
